version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Compile Java
          command: javac -d . src/lab1/Ex2.java

      - run:
          name: Run Java
          command: java lab1.Ex2

workflows:
  build_workflow:
    jobs:
      - build