version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Compile
          command: javac -d . src/lab1/*.java

      - run:
          name: Run Tests
          command: java lab1.AppTest

workflows:
  build_workflow:
    jobs:
      - build